export enum TipoAnalisi {
  EMATOLOGICA = "EMATOLOGICA",
  URINARIA = "URINARIA",
  RADIOLOGICA = "RADIOLOGICA",
  BIOCHIMICA = "BIOCHIMICA",
  CARDIOLOGICA = "CARDIOLOGICA",
  ENDOSCOPIA = "ENDOSCOPIA",
  GENETICA = "GENETICA",
  MICROBIOLOGICA = "MICROBIOLOGICA",
  ONCOLOGICA = "ONCOLOGICA",
  NEUROLOGICA = "NEUROLOGICA"
}
